### ISSUE TITLE
Missing from DB r205-r210 - Intel cpu906E9_plat2A_ver000000EC_2021-04-29_PRD_8C68349C

### ISSUE THREAD

**Issue by am2014a** [platomav/MCExtractor#47] opened 2021-12-10 10:45 UTC
Hello Plato,

I hope this is an actual mistake or am I doing something wrong: Missing from MCExtractor r205-r210 - 
Intel cpu906E9_plat2A_ver000000EC_2021-04-29_PRD_8C68349C

eg from UBU BIOS Updater:
╔═════════════════════════════════════════╗
║        MC Extractor v1.70.0 r210        ║
╚═════════════════════════════════════════╝
╔══════════════════════════════════════════════════════════════════╗
║                              Intel                               ║
╟─┬─────┬────────────┬────────┬──────────┬────┬───────┬───────┬────╢
║#│CPUID│  Platform  │Revision│   Date   │Type│  Size │ Offset│Last║
╟─┼─────┼────────────┼────────┼──────────┼────┼───────┼───────┼────╢
**║1│906E9│ 2A (1,3,5) │   EA   │2021-01-05│PRD │0x19800│  0x18 │ No ║**
╟─┼─────┼────────────┼────────┼──────────┼────┼───────┼───────┼────╢
║2│506E3│36 (1,2,4,5)│   EA   │2021-01-25│PRD │0x19C00│0x19818│Yes ║
╚═╧═════╧════════════╧════════╧══════════╧════╧═══════╧═══════╧════╝
        These microcodes will be entered into your BIOS file

R - Start replacement
A - Start replacement Alternative with MMTool
0 - Cancel
Choice:

Cheers,

Andrew

**Comment by platomav** [comment] 2021-12-10 16:04
Hi Andrew,

Can you explain what the issue is in detail? I'm not sure if I understand.

**Comment by am2014a** [comment] 2021-12-10 18:08
Hi Plato,

 

In r205 to r210 I looked for cpuid 906E9 but only EA microcode is in the MCE.db and/or MCE.py files - not EC microcode (cpu906E9_plat2A_ver000000EC_2021-04-29_PRD_8C68349C). Does that make more sense?

 

Cheers,


Andrew

**Comment by platomav** [comment] 2021-12-10 22:44
The EC entry exists in all MCE DB since r205, so I'm still not sure what you mean. The DB includes text entries for microcodes, not binaries, in case that's the source of your confusion. Since I have verified for that MC entry to exist at the DB, as expected, I'll go ahead and close this issue.

**Closed by platomav** 2021-12-10 22:44 UTC

**Comment by am2014a** [comment] 2021-12-11 09:46
"The DB includes text entries for microcodes, not binaries, in case that's the source of your confusion" 
Sorry Plato - I thought the CPU microcode binaries were also in the db file - my mistake. All good mate. Cheers, Andrew
